# Example configuration file demonstrating hierarchical configuration
# Global settings are defined at the root level and can be overridden by platform and room-level settings

rpc:
  enable: true
  bind: :8080

debug: false

# Global settings (can be overridden)
interval: 30                    # Global check interval: 30 seconds
out_put_path: ./recordings      # Global output path
ffmpeg_path: ""                 # Global ffmpeg path - empty to skip validation

log:
  out_put_folder: ./logs
  save_last_log: true
  save_every_log: false

feature:
  use_native_flv_parser: false
  remove_symbol_other_character: false

# Platform-specific configurations
platform_configs:
  # Douyin platform settings
  douyin:
    name: "抖音"
    min_access_interval_sec: 5   # Rate limiting: max 1 request per 5 seconds to Douyin
    interval: 15                 # Override global: check Douyin rooms every 15 seconds
    out_put_path: ./recordings/douyin  # Override global: separate folder for Douyin recordings
  
  # Bilibili platform settings  
  bilibili:
    name: "哔哩哔哩"
    min_access_interval_sec: 3   # Rate limiting: max 1 request per 3 seconds to Bilibili
    interval: 20                 # Override global: check Bilibili rooms every 20 seconds
    feature:
      use_native_flv_parser: true  # Use native parser for Bilibili
  
  # YY platform settings
  yy:
    name: "YY直播"
    min_access_interval_sec: 10  # Rate limiting: max 1 request per 10 seconds to YY
    out_put_path: ./recordings/yy

# Room configurations
live_rooms:
  # This Douyin room inherits platform settings but overrides interval
  - url: https://live.douyin.com/123456789
    is_listening: true
    quality: 0
    interval: 10                 # Override platform setting: check every 10 seconds for this specific room
    
  # This Bilibili room uses platform settings  
  - url: https://live.bilibili.com/22603245
    is_listening: true
    quality: 0
    
  # This Bilibili room has room-specific overrides
  - url: https://live.bilibili.com/987654321
    is_listening: true 
    quality: 0
    out_put_path: ./recordings/special  # Override both global and platform settings
    ffmpeg_path: /opt/ffmpeg/bin/ffmpeg # Override global setting
    
  # This YY room uses platform settings
  - url: https://www.yy.com/123456
    is_listening: false

# Other global settings
out_put_tmpl: ''
video_split_strategies:
  on_room_name_changed: false
  max_duration: 0s
  max_file_size: 0

cookies: {}

on_record_finished:
  convert_to_mp4: false
  delete_flv_after_convert: false
  custom_commandline: ""

timeout_in_us: 60000000